name: Node.js CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        npm-version: [9.6.6,9.6.7]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use npm ${{ matrix.npm-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run : npm install -g npm@${{ matrix.npm-version }}
    - run: npm install fetch-factory@0.0.2 --package-lock-only
    - run : git diff package.json 
